# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765d64e1966c73613cc172fd83ddd2077c2bb1f3b5483992964250844a6490b40ad7ea607eceaac32c3fb001af82a0ab3ce85ec7679b9ea7dbf33f53cd8ec361

test:
  secret_key_base: e8e4249b3b04885b5339af779aa235997868f95214599c6d0b82a82540ed1c54fe943d01a7076ad26f6ae7b863b47a2f39733590c61020ad3bdb2381ce595dab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
