# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5774a0490c594f6ecfb6587319e60a47f3a97fb537e95172eb16393c0ee53a83d002652462f41e97c0ca724bc8c9563d8f73191f856b6707c99b4a76937ff8d5

test:
  secret_key_base: 812b1e5663a2cd634f212ab3f5dfe03cd3f361595f15306f71cd2a1a9b11f15d3a9a4ea9ac4496bf93ceadc926481095e61b011749b950283cad927122f901a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
