# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f109cd4db00f05b6d37a6492da05fca5a9b405715546d244524b8e1e743754a72c4ddc7c158ebcdf2bdf245f0254ed38fdbf21f426a775af28f186a56ad1afd4

test:
  secret_key_base: e7bf3d623fc2d4a084cae21bac70c45aa332230522ff37a104c59e073d1ccbe367d1d8b4b412359b68305a8b2ec64e5beae8c5f5c764b8af84369df17f7766b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
